export const HELP_CATEGORIES = [
  { id: "getting-started", name: "Getting Started & Account", icon: "LayoutDashboard" },
  { id: "documents", name: "Documents & Uploads", icon: "FileText" },
  { id: "collaboration", name: "Collaboration & Sharing", icon: "Users" },
  { id: "security", name: "Security", icon: "Shield" },
  { id: "version-control", name: "Version Control", icon: "Clock" },
  { id: "ocr-ai", name: "OCR & AI Summarization", icon: "ScanText" },
];

export const HELP_FAQS = [
  {
    id: "faq-email-verify",
    categoryId: "getting-started",
    question: "How do I verify my account email if I missed the verification link?",
    answer: "You can request a new verification link from the login page using the Resend Verification Email option. Also check your spam or junk folder.",
  },
  {
    id: "faq-oauth",
    categoryId: "getting-started",
    question: "Can I sign in using Google or GitHub?",
    answer: "Yes. DocuSphere supports Google and GitHub OAuth2 sign-in.",
  },
  {
    id: "faq-max-size",
    categoryId: "documents",
    question: "What is the maximum file size?",
    answer: "The maximum document upload size is 50 MB.",
  },
  {
    id: "faq-recycle-bin",
    categoryId: "documents",
    question: "How long do deleted documents remain in the Recycle Bin?",
    answer: "Deleted documents are moved to the Recycle Bin. The system permanently purges soft-deleted documents daily at 2:00 AM. Restore them before the cleanup occurs.",
  },
  {
    id: "faq-share-no-download",
    categoryId: "collaboration",
    question: "Can I share a document without allowing downloads?",
    answer: "Yes. When creating a share link, you can disable download permission.",
  },
  {
    id: "faq-share-expiration",
    categoryId: "collaboration",
    question: "Can I set an expiration date for a share link?",
    answer: "Yes. Share links can have an expiration date and time. After expiration, access is revoked.",
  },
  {
    id: "faq-restore-version",
    categoryId: "version-control",
    question: "How do I restore a previous version?",
    answer: "Open the document preview, go to Version History, select the required version, and choose Restore.",
  },
  {
    id: "faq-forget-password",
    categoryId: "security",
    question: "What happens if I forget the password of a protected document?",
    answer: "Document owners can use the document security settings to reset the protection password. Shared-link visitors cannot reset the document password.",
  },
  {
    id: "faq-ai-unavailable",
    categoryId: "ocr-ai",
    question: "Why does my document show \"AI summarization unavailable\"?",
    answer: "OCR text extraction may complete successfully while AI summarization is unavailable. This can occur when the Gemini AI service cannot process the request because of configuration, quota, or service availability issues. Please contact the administrator if the problem continues. Do not expose internal infrastructure information.",
  },
];

export const HELP_GUIDES = [
  {
    id: "guide-upload",
    categoryId: "documents",
    title: "How to Upload a Document",
    description: "Follow this step-by-step guide to upload your files to DocuSphere.",
    readingTime: "2 min read",
    steps: [
      "Open the 'Uploads' page from the sidebar menu.",
      "Drag and drop your file into the drag-and-drop zone or click 'Browse Files' to select a document from your computer.",
      "Make sure your file format is supported (PDF, DOC, XLS, PPT, PNG, JPG) and does not exceed the 50 MB limit.",
      "Wait for the upload progress bar to complete and show the 'Upload Successful' notification.",
      "Your uploaded file will now be listed on the 'My Documents' page.",
      "If OCR or AI summary is required, navigate to the OCR page or use the Document Preview actions."
    ],
    relatedFaqIds: ["faq-max-size", "faq-recycle-bin"],
    relatedTutorialId: "t-upload"
  },
  {
    id: "guide-password-protect",
    categoryId: "security",
    title: "How to Password-Protect a Document",
    description: "Keep sensitive files secure by adding password protection.",
    readingTime: "3 min read",
    steps: [
      "Go to the 'My Documents' page and select the document you want to protect.",
      "Click the three-dot action menu and choose 'Security' or 'Password Protect'.",
      "Enter a strong password and confirm it.",
      "Save changes. Now, any user who wants to preview, download, or edit the file must enter this password.",
      "As the owner, you can always change or remove the password under document security settings."
    ],
    relatedFaqIds: ["faq-forget-password"],
    relatedTutorialId: "t-protect"
  },
  {
    id: "guide-team-invite",
    categoryId: "collaboration",
    title: "How to Create a Team and Invite Members",
    description: "Build a collaborative workspace to work on files together.",
    readingTime: "4 min read",
    steps: [
      "Select 'Team' from the primary sidebar navigation.",
      "Click the 'New Team' button in the top right corner.",
      "Enter a team name, description, and click 'Create Team'.",
      "On the team details screen, click 'Invite Member'.",
      "Type the email address of the team member, select their role (Admin or Member), and click 'Send Invitation'."
    ],
    relatedFaqIds: ["faq-share-no-download", "faq-share-expiration"],
    relatedTutorialId: "t-create-team"
  }
];

export const HELP_TUTORIALS = [
  // Documents
  {
    id: "t-upload",
    title: "How to Upload a Document",
    description: "Learn how to upload PDF, Word, Excel, and image documents to DocuSphere.",
    category: "Documents",
    duration: "1:02",
    youtubeUrl: "https://youtu.be/D2fd7vrNdCE?si=nB5nSidGlgywMlA4U",
    videoId: "D2fd7vrNdCE",
    available: true,
  },
  {
    id: "t-manage-documents",
    title: "How to Manage Documents",
    description: "Organize your files, create directories, and navigate the document dashboard.",
    category: "Documents",
    duration: "2:12",
    youtubeUrl: "https://youtu.be/M2N2eeWm1wE?si=5dLHsJBgEWcc6pPl",
    videoId: "M2N2eeWm1wE",
    available: true,
  },
  {
    id: "t-document-actions",
    title: "How to Use Document Actions",
    description: "Perform bulk operations, download, rename, star, or delete files.",
    category: "Documents",
    duration: "2:30",
    youtubeUrl: "https://youtu.be/ssQD3ShDI0c?si=2cf9vXQMFfenVw45",
    videoId: "ssQD3ShDI0c",
    available: true,
  },
  {
    id: "t-search-filter",
    title: "How to Search and Filter Documents",
    description: "Quickly locate files using search queries, favorites, and sort parameters.",
    category: "Documents",
    duration: "2:10",
    youtubeUrl: "",
    videoId: "",
    available: false,
  },
  {
    id: "t-rename-organize",
    title: "How to Rename and Organize Documents",
    description: "Manage your files by renaming, duplicating, or moving them.",
    category: "Documents",
    duration: "1:30",
    youtubeUrl: "",
    videoId: "",
    available: false,
  },
  {
    id: "t-recycle-bin",
    title: "How to Use the Recycle Bin",
    description: "Learn how to restore deleted items or permanently purge trash files.",
    category: "Documents",
    duration: "1:15",
    youtubeUrl: "",
    videoId: "",
    available: false,
  },
  
  // OCR & AI
  {
    id: "t-ocr-extract",
    title: "How to Extract Text with OCR",
    description: "Convert image files and scanned PDFs into selectable, searchable digital text.",
    category: "OCR & AI",
    duration: "1:34",
    youtubeUrl: "https://youtu.be/sF4RPxbnSV4?si=oXiiKGExPCOkBb3j",
    videoId: "sF4RPxbnSV4",
    available: true,
  },
  {
    id: "t-ai-summary",
    title: "How to Generate an AI Summary",
    description: "Get key points, automatic tags, and short summaries using Gemini AI integration.",
    category: "OCR & AI",
    duration: "1:34",
    youtubeUrl: "https://youtu.be/sF4RPxbnSV4?si=oXiiKGExPCOkBb3j",
    videoId: "sF4RPxbnSV4",
    available: true,
  },
  {
    id: "t-ocr-status",
    title: "How to Understand OCR Processing Status",
    description: "Overview of pending, completed, and failed status updates during async document processing.",
    category: "OCR & AI",
    duration: "1:55",
    youtubeUrl: "",
    videoId: "",
    available: false,
  },

  // Collaboration
  {
    id: "t-create-team",
    title: "How to Create a Team",
    description: "Create shared workspaces for teams and select appropriate user permissions.",
    category: "Collaboration",
    duration: "1:18",
    youtubeUrl: "https://youtu.be/zhIjTBPeFFU?si=iOnZa2dGwoYqeoq0",
    videoId: "zhIjTBPeFFU",
    available: true,
  },
  {
    id: "t-invite-members",
    title: "How to Invite Team Members",
    description: "Invite users by email to join your workspace and assign user roles.",
    category: "Collaboration",
    duration: "1:05",
    youtubeUrl: "https://youtu.be/Rt4OrIFGCyM?si=_aU_i0pn9wqPkZkr",
    videoId: "Rt4OrIFGCyM",
    available: true,
  },
  {
    id: "t-team-chat",
    title: "How to Use Team Chat",
    description: "Communicate in real-time with team members via team workspace chat rooms.",
    category: "Collaboration",
    duration: "1:45",
    youtubeUrl: "https://youtu.be/TbxC5QdwfYw?si=jIG-JinGO55uZufP",
    videoId: "TbxC5QdwfYw",
    available: true,
  },
  {
    id: "t-document-comments",
    title: "How to Use Document Comments",
    description: "Write and reply to contextual comments directly inside document previews.",
    category: "Collaboration",
    duration: "2:15",
    youtubeUrl: "",
    videoId: "",
    available: false,
  },

  // Sharing & Security
  {
    id: "t-share-doc",
    title: "How to Share a Document",
    description: "Create share links for public or internal sharing of documents.",
    category: "Sharing & Security",
    duration: "2:05",
    youtubeUrl: "https://youtu.be/NRfjHbIhepw?si=3kxLr753Y6NuzvWf",
    videoId: "NRfjHbIhepw",
    available: true,
  },
  {
    id: "t-share-perms",
    title: "How to Set Share Permissions",
    description: "Configure view, edit, or download permissions when sharing links.",
    category: "Sharing & Security",
    duration: "2:05",
    youtubeUrl: "https://youtu.be/NRfjHbIhepw?si=3kxLr753Y6NuzvWf",
    videoId: "NRfjHbIhepw",
    available: true,
  },
  {
    id: "t-share-expiry",
    title: "How to Set Share Expiration",
    description: "Protect sensitive info by specifying automatic expiration date and times on links.",
    category: "Sharing & Security",
    duration: "1:50",
    youtubeUrl: "",
    videoId: "",
    available: false,
  },
  {
    id: "t-protect",
    title: "How to Password-Protect a Document",
    description: "Encrypt files with custom passwords for an additional layer of document protection.",
    category: "Sharing & Security",
    duration: "2:25",
    youtubeUrl: "",
    videoId: "",
    available: false,
  },

  // Version Control
  {
    id: "t-version-history",
    title: "How to View Version History",
    description: "Browse older saved versions of a document to review audit changes over time.",
    category: "Version Control",
    duration: "1:52",
    youtubeUrl: "https://youtu.be/8K1_nItSR_M?si=8AsE6W-o0pxRKWm8",
    videoId: "8K1_nItSR_M",
    available: true,
  },
  {
    id: "t-restore-version",
    title: "How to Restore an Older Version",
    description: "Revert back to a previous revision or restore deleted versions to current document state.",
    category: "Version Control",
    duration: "1:52",
    youtubeUrl: "https://youtu.be/8K1_nItSR_M?si=8AsE6W-o0pxRKWm8",
    videoId: "8K1_nItSR_M",
    available: true,
  },

  // Online Editors
  {
    id: "t-editor-docx",
    title: "How to Use Online Editor for Docx Files",
    description: "Create, view, and edit text documents directly inside your browser with the online editor.",
    category: "Online Editors",
    duration: "2:08",
    youtubeUrl: "https://youtu.be/xDJtyDfMsf0?si=hqSdwOh1s5kshwQ7",
    videoId: "xDJtyDfMsf0",
    available: true,
  },
  {
    id: "t-editor-presentation",
    title: "How to Use Online Editor for Presentations",
    description: "Design presentation slides and customize layouts using the integrated presentation editor.",
    category: "Online Editors",
    duration: "2:22",
    youtubeUrl: "https://youtu.be/UNC7lDeXlLA?si=Dv4lk8cr8YSizqX5",
    videoId: "UNC7lDeXlLA",
    available: true,
  },
  {
    id: "t-editor-excel",
    title: "How to Use Online Editor for Spreadsheets",
    description: "Edit Excel and sheet files online, create tables, and perform formula calculations.",
    category: "Online Editors",
    duration: "2:14",
    youtubeUrl: "https://youtu.be/UsHDXNUTlF0?si=M3gpZFnE_GRNZhhk",
    videoId: "UsHDXNUTlF0",
    available: true,
  }
];
